baseURL = 'https://insileco.io/'
languageCode = 'en'
title = 'inSileco'

# Link custom CSS and JS assets
#   (relative to /static/css and /static/js respectively)
custom_css = ["perso.css"]
custom_js = []

[languages]
  [languages.fr]
    languageCode = "fr-ca"
    weight = 1
    contentDir = "content/fr"
    [languages.fr.params]
        subtitle = "Gestion écosystémique & Science des données en biodiversité"
        keywords = ["Solutions", "Accompagnement", "Formations"]
        title_expertise = "Notre expertise"
        subtitle_expertise = "Nous sommes d’éminents scientifiques et experts en données spécialisés dans les sciences de la biodiversité. Notre expertise académique couvre l'écologie théorique du réseau trophique et le développement de méthodologies essentielles pour la gestion écosystémique, comme détaillé dans notre longue liste de publications évaluées par des pairs. En tant que data scientists, nous excellons dans un large éventail d’analyses statistiques, en les appliquant à des ensembles de données vastes et diversifiés à l’aide de technologies avancées. Avec plus d'une décennie d'expérience professionnelle et universitaire, nous avons perfectionné nos compétences en aidant les scientifiques universitaires et gouvernementaux à analyser et à visualiser les données sur la biodiversité, et à créer des pipelines analytiques robustes et des outils interactifs."
        title_team = "Notre équipe"
        subtitle_team = ""
        footer = 'Le code source de ce site est disponible sur <a href="https://github.com/inSilecoInc/insilecoinc.github.io">GitHub</a> sous licence <a href="http://opensource.org/licenses/mit-license.php">MIT</a>.</br>&copy; inSileco Inc. 2024'
    [[languages.fr.menu.main]]
        name = "Acceuil"
        url = "/"
        weight = 1
    [[languages.fr.menu.main]]
        name = "Mission"
        url = "#mission"
        weight = 1
    [[languages.fr.menu.main]]
        name = "Expertise"
        url = "#expertise"
        weight = 2
    [[languages.fr.menu.main]]
        name = "Équipe"
        url = "#team"
        weight = 3
    [[languages.fr.menu.main]]
        name = "Démarche"
        url = "#approach"
        weight = 4
    [[languages.fr.menu.main]]
        name = "Portfolio"
        url = "/portfolio/"
        weight = 5
    [[languages.fr.menu.main]]
        name = "Publications"
        url = "publications"
        weight = 6
    [[languages.fr.menu.main]]
        name = "Blogue"
        url = "https://blog.insileco.io"
        weight = 7
    [[languages.fr.menu.main]]
        name = "Contactez-nous"
        url = "#contact"
        weight = 8
  [languages.en]
    languageCode = "en-ca"
    weight = 2
    contentDir = "content/en"
    [languages.en.params]
        subtitle = "Environmental management & Biodiversity Data science"
        keywords = ["Solutions", "Support", "Training"]
        title_expertise = "Our expertise"
        subtitle_expertise = "We are distinguished scientists and data experts specializing in biodiversity sciences. Our academic expertise spans theoretical food web ecology and the development of essential methodologies for ecosystem-based management, as detailed in our extensive list of peer-reviewed publications. As data scientists, we excel in a wide range of statistical analyses, applying them to large and diverse datasets using advanced technologies. With over a decade of professional and academic experience, we have honed our skills in supporting academic and governmental scientists in analyzing and visualizing biodiversity data, and in creating robust analytical pipelines and interactive tools."
        title_team = "Our team"
        subtitle_team = ""
        footer = 'The source code of this website is available on <a href="https://github.com/inSilecoInc/insilecoinc.github.io">GitHub</a> licensed under <a href="http://opensource.org/licenses/mit-license.php">MIT</a>.</br>&copy; inSileco Inc. 2024.'
    [[languages.en.menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[languages.en.menu.main]]
        name = "Mission"
        url = "#mission"
        weight = 1
    [[languages.en.menu.main]]
        name = "Expertise"
        url = "#expertise"
        weight = 2
    [[languages.en.menu.main]]
        name = "Team"
        url = "#team"
        weight = 3
    [[languages.en.menu.main]]
        name = "Approach"
        url = "#approach"
        weight = 4
    [[languages.en.menu.main]]
        name = "Portfolio"
        url = "/portfolio/"
        weight = 5
    [[languages.en.menu.main]]
        name = "Publications"
        url = "publications"
        weight = 6
    [[languages.en.menu.main]]
        name = "Blog"
        url = "https://blog.insileco.io"
        weight = 7
    [[languages.en.menu.main]]
        name = "Contact us"
        url = "#contact"
        weight = 8

[params]
col_emphase = "#b4637a"
